version: "3.8"
services:
  backend:
    build: ./pi-engine-backend
    ports:
      - "8000:8000"

  frontend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: python -m http.server 8080
    ports:
      - "8080:8080"
